<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\..\..\..\common.props" />
    <Import Project="..\..\..\..\configureawait.props" />
    
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\server\Elsa.Server.Api\Elsa.Server.Api.csproj" />
      <ProjectReference Include="..\Elsa.WorkflowTesting\Elsa.WorkflowTesting.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Update="ConfigureAwait.Fody" Version="3.4.0" />
      <PackageReference Update="Fody" Version="6.9.3">
        <PrivateAssets>all</PrivateAssets>
      </PackageReference>
      <PackageReference Update="Microsoft.SourceLink.GitHub" Version="10.0.203" />
    </ItemGroup>

</Project>
