<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\..\..\common.props" />
    <Import Project="..\..\..\configureawait.props" />

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Description>
            Elsa is a set of workflow libraries and tools that enable lean and mean workflowing capabilities in any .NET Core application.
            This package provides API endpoints to interact with the workflow host.
        </Description>
        <PackageTags>elsa, workflows, asp.net core</PackageTags>
        <OpenApiGenerateDocumentsOnBuild>false</OpenApiGenerateDocumentsOnBuild>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
        <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="10.0.0" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="10.0.7" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
        <PackageReference Include="NodaTime.Serialization.SystemTextJson" Version="1.3.1" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />
        <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="10.1.7" />
        <PackageReference Include="Swashbuckle.AspNetCore.Filters" Version="10.0.1" />
        <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="10.1.7" />
        <PackageReference Include="System.Linq.Async" Version="7.0.1">
            <ExcludeAssets>compile</ExcludeAssets>
        </PackageReference>
        <PackageReference Include="System.Text.Encodings.Web" Version="10.0.7" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\core\Elsa\Elsa.csproj" />
        <ProjectReference Include="..\Elsa.Server.Core\Elsa.Server.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Update="Microsoft.SourceLink.GitHub" Version="10.0.203" />
    </ItemGroup>

</Project>
